# Users
## Зарегистрироваться

POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "userType": "Pro",
  "name": "Jack",
  "avatar": "torrance.png",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/66533461ab151a4c21b189a2/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/Rinat/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

## Check user's token
GET http://localhost:5000/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1MzM0NjFhYjE1MWE0YzIxYjE4OWEyIiwiaWF0IjoxNzE2NzI5MTgyLCJleHAiOjE3MTY5MDE5ODJ9.w_uNGylEYdgOUlKH4M9X5dvOagt95FrA3X2Dwol1DRw

###

###

## Login user
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

# id 66533461ab151a4c21b189a2
# "token": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1MzM0NjFhYjE1MWE0YzIxYjE4OWEyIiwiaWF0IjoxNzE2NzI5MTgyLCJleHAiOjE3MTY5MDE5ODJ9.w_uNGylEYdgOUlKH4M9X5dvOagt95FrA3X2Dwol1DRw",
###

