# get comments
GET http://localhost:5000/offers/665359af6dd17989f575c692/comments HTTP/1.1

###

# create comment
POST http://localhost:5000/offers/665359af6dd17989f575c692/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1MzM0NjFhYjE1MWE0YzIxYjE4OWEyIiwiaWF0IjoxNzE2NzI5MTgyLCJleHAiOjE3MTY5MDE5ODJ9.w_uNGylEYdgOUlKH4M9X5dvOagt95FrA3X2Dwol1DRw

{
  "text": "string",
  "rating": 5,
  "offerId": "665359af6dd17989f575c692",
  "createdAt": "2012"
}
###
